[features]
seeds = false
[programs.devnet]
myepicproject = "GVTNqu7Twv1qfC5gQo8sbUAZuKe3Ebs5V4CT5W65WCyR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/maxbelushkin/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
